// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID        uuid.UUID
	UserID    sql.NullInt32
	FolderID  uuid.NullUUID
	Name      string
	FilePath  string
	SizeBytes int64
	MimeType  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type FileShare struct {
	FileID       uuid.NullUUID
	SharedUserID sql.NullInt32
	CreatedAt    sql.NullTime
}

type Folder struct {
	ID        uuid.UUID
	UserID    sql.NullInt32
	Name      string
	ParentID  uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type FolderShare struct {
	FolderID     uuid.NullUUID
	SharedUserID sql.NullInt32
	CreatedAt    sql.NullTime
}

type RefreshToken struct {
	TokenHash string
	UserID    int32
	ExpiresAt time.Time
	CreatedAt time.Time
	Revoked   bool
}

type User struct {
	ID                      int32
	Email                   string
	PasswordHash            string
	IsVerified              bool
	VerificationToken       sql.NullString
	VerificationTokenExpiry sql.NullTime
	UsedStorage             int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
}
