// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (folder_id, user_id, name, file_path, size_bytes, mime_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, folder_id, name, file_path, size_bytes, mime_type, created_at, updated_at
`

type CreateFileParams struct {
	FolderID  uuid.NullUUID
	UserID    sql.NullInt32
	Name      string
	FilePath  string
	SizeBytes int64
	MimeType  sql.NullString
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.FolderID,
		arg.UserID,
		arg.Name,
		arg.FilePath,
		arg.SizeBytes,
		arg.MimeType,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Name,
		&i.FilePath,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFiles = `-- name: DeleteFiles :execrows
DELETE FROM files
WHERE id = ANY($1::uuid[]) AND user_id = $2
`

type DeleteFilesParams struct {
	Column1 []uuid.UUID
	UserID  sql.NullInt32
}

func (q *Queries) DeleteFiles(ctx context.Context, arg DeleteFilesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFiles, pq.Array(arg.Column1), arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, folder_id, name, file_path, size_bytes, mime_type, created_at, updated_at FROM files WHERE id = $1 AND user_id = $2
`

type GetFileByIDParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Name,
		&i.FilePath,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByNameInFolder = `-- name: GetFileByNameInFolder :one
SELECT id, user_id, folder_id, name, file_path, size_bytes, mime_type, created_at, updated_at FROM files
WHERE folder_id = $1 AND name = $2
`

type GetFileByNameInFolderParams struct {
	FolderID uuid.NullUUID
	Name     string
}

func (q *Queries) GetFileByNameInFolder(ctx context.Context, arg GetFileByNameInFolderParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByNameInFolder, arg.FolderID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Name,
		&i.FilePath,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesInFolder = `-- name: ListFilesInFolder :many
SELECT id, user_id, folder_id, name, file_path, size_bytes, mime_type, created_at, updated_at
FROM files
WHERE (folder_id = $2 OR ($2 IS NULL AND folder_id IS NULL)) AND user_id = $1
ORDER BY name
`

type ListFilesInFolderParams struct {
	UserID   sql.NullInt32
	FolderID uuid.NullUUID
}

func (q *Queries) ListFilesInFolder(ctx context.Context, arg ListFilesInFolderParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesInFolder, arg.UserID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Name,
			&i.FilePath,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesRecursive = `-- name: ListFilesRecursive :many
WITH RECURSIVE subfolders AS (
    SELECT folders.id AS sf_folder_id
    FROM folders
    WHERE folders.id = $2 AND folders.user_id = $1

    UNION ALL

    SELECT f.id AS sf_folder_id
    FROM folders f
    INNER JOIN subfolders s ON f.parent_id = s.sf_folder_id
    WHERE f.user_id = $1
)
SELECT 
    f.id AS file_id,
    f.folder_id AS folder_id,
    f.user_id AS user_id,
    f.name AS name,
    f.file_path AS file_path,
    f.size_bytes AS size_bytes,
    f.mime_type AS mime_type,
    f.created_at AS created_at,
    f.updated_at AS updated_at
FROM files f
INNER JOIN subfolders sf ON f.folder_id = sf.sf_folder_id
WHERE f.user_id = $1
ORDER BY f.name
`

type ListFilesRecursiveParams struct {
	UserID sql.NullInt32
	ID     uuid.UUID
}

type ListFilesRecursiveRow struct {
	FileID    uuid.UUID
	FolderID  uuid.NullUUID
	UserID    sql.NullInt32
	Name      string
	FilePath  string
	SizeBytes int64
	MimeType  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListFilesRecursive(ctx context.Context, arg ListFilesRecursiveParams) ([]ListFilesRecursiveRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesRecursive, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRecursiveRow
	for rows.Next() {
		var i ListFilesRecursiveRow
		if err := rows.Scan(
			&i.FileID,
			&i.FolderID,
			&i.UserID,
			&i.Name,
			&i.FilePath,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :execrows
UPDATE files
SET
    size_bytes = $3 AND
    mime_type  = $4,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
`

type UpdateFileMetadataParams struct {
	ID        uuid.UUID
	UserID    sql.NullInt32
	SizeBytes int64
	MimeType  sql.NullString
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFileMetadata,
		arg.ID,
		arg.UserID,
		arg.SizeBytes,
		arg.MimeType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFileNameAndPath = `-- name: UpdateFileNameAndPath :execrows
UPDATE files
SET name = $3 AND
    file_path = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateFileNameAndPathParams struct {
	ID       uuid.UUID
	UserID   sql.NullInt32
	Name     string
	FilePath string
}

func (q *Queries) UpdateFileNameAndPath(ctx context.Context, arg UpdateFileNameAndPathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFileNameAndPath,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.FilePath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFileParentAndPath = `-- name: UpdateFileParentAndPath :execrows
UPDATE files
SET folder_id = $3 AND
    file_path = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateFileParentAndPathParams struct {
	ID       uuid.UUID
	UserID   sql.NullInt32
	FolderID uuid.NullUUID
	FilePath string
}

func (q *Queries) UpdateFileParentAndPath(ctx context.Context, arg UpdateFileParentAndPathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFileParentAndPath,
		arg.ID,
		arg.UserID,
		arg.FolderID,
		arg.FilePath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
