// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_shares.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const canUserAccessFile = `-- name: CanUserAccessFile :one
SELECT 1
FROM files f
LEFT JOIN file_shares fs ON fs.file_id = f.id
WHERE f.id = $1 AND (f.user_id = $2 OR fs.shared_user_id = $2)
LIMIT 1
`

type CanUserAccessFileParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

func (q *Queries) CanUserAccessFile(ctx context.Context, arg CanUserAccessFileParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, canUserAccessFile, arg.ID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createFileShare = `-- name: CreateFileShare :one
INSERT INTO file_shares (file_id, shared_user_id, permission)
VALUES ($1, $2, 'read')
RETURNING file_id, shared_user_id, created_at
`

type CreateFileShareParams struct {
	FileID       uuid.NullUUID
	SharedUserID sql.NullInt32
}

func (q *Queries) CreateFileShare(ctx context.Context, arg CreateFileShareParams) (FileShare, error) {
	row := q.db.QueryRowContext(ctx, createFileShare, arg.FileID, arg.SharedUserID)
	var i FileShare
	err := row.Scan(&i.FileID, &i.SharedUserID, &i.CreatedAt)
	return i, err
}

const deleteFileShare = `-- name: DeleteFileShare :execrows
DELETE FROM file_shares
WHERE file_id = $1 AND shared_user_id = $2
`

type DeleteFileShareParams struct {
	FileID       uuid.NullUUID
	SharedUserID sql.NullInt32
}

func (q *Queries) DeleteFileShare(ctx context.Context, arg DeleteFileShareParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFileShare, arg.FileID, arg.SharedUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFileShare = `-- name: GetFileShare :one
SELECT file_id, shared_user_id, created_at
FROM file_shares
WHERE file_id = $1 AND shared_user_id = $2
`

type GetFileShareParams struct {
	FileID       uuid.NullUUID
	SharedUserID sql.NullInt32
}

func (q *Queries) GetFileShare(ctx context.Context, arg GetFileShareParams) (FileShare, error) {
	row := q.db.QueryRowContext(ctx, getFileShare, arg.FileID, arg.SharedUserID)
	var i FileShare
	err := row.Scan(&i.FileID, &i.SharedUserID, &i.CreatedAt)
	return i, err
}

const listFileShares = `-- name: ListFileShares :many
SELECT file_id, shared_user_id, created_at
FROM file_shares
WHERE file_id = $1
`

func (q *Queries) ListFileShares(ctx context.Context, fileID uuid.NullUUID) ([]FileShare, error) {
	rows, err := q.db.QueryContext(ctx, listFileShares, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(&i.FileID, &i.SharedUserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
