// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (folder_id, user_id, name, file_path, size_bytes, mime_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, folder_id, user_id, name, file_path, size_bytes, mime_type, created_at, updated_at
`

type CreateFileParams struct {
	FolderID  uuid.NullUUID
	UserID    sql.NullInt32
	Name      string
	FilePath  string
	SizeBytes int64
	MimeType  sql.NullString
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.FolderID,
		arg.UserID,
		arg.Name,
		arg.FilePath,
		arg.SizeBytes,
		arg.MimeType,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.FilePath,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :execrows
DELETE FROM files
WHERE id = $1 AND user_id = $2
`

type DeleteFileParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, folder_id, user_id, name, file_path, size_bytes, mime_type, created_at, updated_at FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.FilePath,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByNameInFolder = `-- name: GetFileByNameInFolder :one
SELECT id, folder_id, user_id, name, file_path, size_bytes, mime_type, created_at, updated_at FROM files
WHERE folder_id = $1 AND name = $2
`

type GetFileByNameInFolderParams struct {
	FolderID uuid.NullUUID
	Name     string
}

func (q *Queries) GetFileByNameInFolder(ctx context.Context, arg GetFileByNameInFolderParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByNameInFolder, arg.FolderID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.FilePath,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesInFolder = `-- name: ListFilesInFolder :many
SELECT id, folder_id, user_id, name, file_path, size_bytes, mime_type, created_at, updated_at
FROM files
WHERE (folder_id = $1 OR ($1 IS NULL AND folder_id IS NULL)) AND user_id = $2
ORDER BY name
`

type ListFilesInFolderParams struct {
	FolderID uuid.NullUUID
	UserID   sql.NullInt32
}

func (q *Queries) ListFilesInFolder(ctx context.Context, arg ListFilesInFolderParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesInFolder, arg.FolderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.UserID,
			&i.Name,
			&i.FilePath,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesRecursive = `-- name: ListFilesRecursive :many
WITH RECURSIVE subfolders AS (
    SELECT folders.id AS sf_folder_id
    FROM folders
    WHERE folders.id = $1 AND folders.user_id = $2

    UNION ALL

    SELECT f.id AS sf_folder_id
    FROM folders f
    INNER JOIN subfolders s ON f.parent_id = s.sf_folder_id
    WHERE f.user_id = $2
)
SELECT 
    f.id AS file_id,
    f.folder_id AS folder_id,
    f.user_id AS user_id,
    f.name AS name,
    f.file_path AS file_path,
    f.size_bytes AS size_bytes,
    f.mime_type AS mime_type,
    f.created_at AS created_at,
    f.updated_at AS updated_at
FROM files f
INNER JOIN subfolders sf ON f.folder_id = sf.sf_folder_id
WHERE f.user_id = $2
ORDER BY f.name
`

type ListFilesRecursiveParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

type ListFilesRecursiveRow struct {
	FileID    uuid.UUID
	FolderID  uuid.NullUUID
	UserID    sql.NullInt32
	Name      string
	FilePath  string
	SizeBytes int64
	MimeType  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListFilesRecursive(ctx context.Context, arg ListFilesRecursiveParams) ([]ListFilesRecursiveRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesRecursive, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRecursiveRow
	for rows.Next() {
		var i ListFilesRecursiveRow
		if err := rows.Scan(
			&i.FileID,
			&i.FolderID,
			&i.UserID,
			&i.Name,
			&i.FilePath,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :execrows
UPDATE files
SET name = $2, updated_at = now()
WHERE id = $1 AND user_id = $3
`

type UpdateFileMetadataParams struct {
	ID     uuid.UUID
	Name   string
	UserID sql.NullInt32
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFileMetadata, arg.ID, arg.Name, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFilePath = `-- name: UpdateFilePath :execrows
UPDATE files
SET file_path = $2, updated_at = now()
WHERE id = $1 AND user_id = $3
`

type UpdateFilePathParams struct {
	ID       uuid.UUID
	FilePath string
	UserID   sql.NullInt32
}

func (q *Queries) UpdateFilePath(ctx context.Context, arg UpdateFilePathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFilePath, arg.ID, arg.FilePath, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
