// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (user_id, name, parent_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, parent_id, created_at, updated_at
`

type CreateFolderParams struct {
	UserID   sql.NullInt32
	Name     string
	ParentID uuid.NullUUID
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, arg.UserID, arg.Name, arg.ParentID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders
WHERE id = $1 AND user_id = $2
`

type DeleteFolderParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFolder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, user_id, name, parent_id, created_at, updated_at FROM folders WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByNameInParent = `-- name: GetFolderByNameInParent :one
SELECT id, user_id, name, parent_id, created_at, updated_at
FROM folders
WHERE 
    user_id = $1 AND
    name = $2 
  AND (
    (parent_id = $3 AND $3 IS NOT NULL)
    OR (parent_id IS NULL AND $3 IS NULL)
  )
LIMIT 1
`

type GetFolderByNameInParentParams struct {
	UserID   sql.NullInt32
	Name     string
	ParentID uuid.NullUUID
}

func (q *Queries) GetFolderByNameInParent(ctx context.Context, arg GetFolderByNameInParentParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByNameInParent, arg.UserID, arg.Name, arg.ParentID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderFullPath = `-- name: GetFolderFullPath :one
WITH RECURSIVE folder_path AS (
    -- Anchor: start with the target folder
    SELECT 
        f.id AS folder_id,
        f.name AS folder_name,
        f.parent_id AS folder_parent_id,
        f.user_id AS folder_user_id,
        1 AS level
    FROM folders f
    WHERE f.id = $1 AND f.user_id = $2

    UNION ALL

    -- Recursive: join parent folders
    SELECT 
        f.id AS folder_id,
        f.name AS folder_name,
        f.parent_id AS folder_parent_id,
        f.user_id AS folder_user_id,
        fp.level + 1 AS level
    FROM folders f
    JOIN folder_path fp ON f.id = fp.folder_parent_id
    WHERE f.user_id = $2
)
SELECT string_agg(folder_name, '/' ORDER BY level DESC)::TEXT AS full_path
FROM folder_path
`

type GetFolderFullPathParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

func (q *Queries) GetFolderFullPath(ctx context.Context, arg GetFolderFullPathParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getFolderFullPath, arg.ID, arg.UserID)
	var full_path string
	err := row.Scan(&full_path)
	return full_path, err
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, user_id, name, parent_id, created_at, updated_at
FROM folders
WHERE user_id = $1
  AND (
    (parent_id = $2 AND $2 IS NOT NULL)
    OR (parent_id IS NULL AND $2 IS NULL)
  )
ORDER BY name
`

type ListFoldersByParentParams struct {
	UserID   sql.NullInt32
	ParentID uuid.NullUUID
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersByParent, arg.UserID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersRecursive = `-- name: ListFoldersRecursive :many
WITH RECURSIVE subfolders AS (
    SELECT f0.id, f0.user_id, f0.name, f0.parent_id, f0.created_at, f0.updated_at
    FROM folders f0
    WHERE f0.id = $1 AND f0.user_id = $2

    UNION ALL

    SELECT f.id, f.user_id, f.name, f.parent_id, f.created_at, f.updated_at
    FROM folders f
    INNER JOIN subfolders s ON f.parent_id = s.id
    WHERE f.user_id = $2
)
SELECT id, user_id, name, parent_id, created_at, updated_at
FROM subfolders
`

type ListFoldersRecursiveParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

type ListFoldersRecursiveRow struct {
	ID        uuid.UUID
	UserID    sql.NullInt32
	Name      string
	ParentID  uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListFoldersRecursive(ctx context.Context, arg ListFoldersRecursiveParams) ([]ListFoldersRecursiveRow, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersRecursive, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFoldersRecursiveRow
	for rows.Next() {
		var i ListFoldersRecursiveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolderMetadata = `-- name: UpdateFolderMetadata :execrows
UPDATE folders
SET name = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateFolderMetadataParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
	Name   string
}

func (q *Queries) UpdateFolderMetadata(ctx context.Context, arg UpdateFolderMetadataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFolderMetadata, arg.ID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFolderParent = `-- name: UpdateFolderParent :execrows
UPDATE folders
SET parent_id = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateFolderParentParams struct {
	ID       uuid.UUID
	UserID   sql.NullInt32
	ParentID uuid.NullUUID
}

func (q *Queries) UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFolderParent, arg.ID, arg.UserID, arg.ParentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
