// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder_shares.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const canUserAccessFolder = `-- name: CanUserAccessFolder :one
SELECT 1
FROM folders fo
LEFT JOIN folder_shares fs ON fs.folder_id = fo.id
WHERE fo.id = $1 AND (fo.user_id = $2 OR fs.shared_user_id = $2)
LIMIT 1
`

type CanUserAccessFolderParams struct {
	ID     uuid.UUID
	UserID sql.NullInt32
}

func (q *Queries) CanUserAccessFolder(ctx context.Context, arg CanUserAccessFolderParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, canUserAccessFolder, arg.ID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createFolderShare = `-- name: CreateFolderShare :one
INSERT INTO folder_shares (folder_id, shared_user_id, permission)
VALUES ($1, $2, 'read')
RETURNING folder_id, shared_user_id, created_at
`

type CreateFolderShareParams struct {
	FolderID     uuid.NullUUID
	SharedUserID sql.NullInt32
}

func (q *Queries) CreateFolderShare(ctx context.Context, arg CreateFolderShareParams) (FolderShare, error) {
	row := q.db.QueryRowContext(ctx, createFolderShare, arg.FolderID, arg.SharedUserID)
	var i FolderShare
	err := row.Scan(&i.FolderID, &i.SharedUserID, &i.CreatedAt)
	return i, err
}

const deleteFolderShare = `-- name: DeleteFolderShare :execrows
DELETE FROM folder_shares
WHERE folder_id = $1 AND shared_user_id = $2
`

type DeleteFolderShareParams struct {
	FolderID     uuid.NullUUID
	SharedUserID sql.NullInt32
}

func (q *Queries) DeleteFolderShare(ctx context.Context, arg DeleteFolderShareParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFolderShare, arg.FolderID, arg.SharedUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFolderShare = `-- name: GetFolderShare :one
SELECT folder_id, shared_user_id, created_at
FROM folder_shares
WHERE folder_id = $1 AND shared_user_id = $2
`

type GetFolderShareParams struct {
	FolderID     uuid.NullUUID
	SharedUserID sql.NullInt32
}

func (q *Queries) GetFolderShare(ctx context.Context, arg GetFolderShareParams) (FolderShare, error) {
	row := q.db.QueryRowContext(ctx, getFolderShare, arg.FolderID, arg.SharedUserID)
	var i FolderShare
	err := row.Scan(&i.FolderID, &i.SharedUserID, &i.CreatedAt)
	return i, err
}

const listFolderShares = `-- name: ListFolderShares :many
SELECT folder_id, shared_user_id, created_at
FROM folder_shares
WHERE folder_id = $1
`

func (q *Queries) ListFolderShares(ctx context.Context, folderID uuid.NullUUID) ([]FolderShare, error) {
	rows, err := q.db.QueryContext(ctx, listFolderShares, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolderShare
	for rows.Next() {
		var i FolderShare
		if err := rows.Scan(&i.FolderID, &i.SharedUserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
