// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID                      int32
	Email                   string
	PasswordHash            string
	IsVerified              bool
	VerificationToken       sql.NullString
	VerificationTokenExpiry sql.NullTime
	CreatedAt               time.Time
	UpdatedAt               time.Time
}
