// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    is_verified,
    verification_token,
    verification_token_expiry,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, email, password_hash, is_verified, verification_token, verification_token_expiry, used_storage, created_at, updated_at
`

type CreateUserParams struct {
	Email                   string
	PasswordHash            string
	IsVerified              bool
	VerificationToken       sql.NullString
	VerificationTokenExpiry sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.IsVerified,
		arg.VerificationToken,
		arg.VerificationTokenExpiry,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiry,
		&i.UsedStorage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_verified, verification_token, verification_token_expiry, used_storage, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiry,
		&i.UsedStorage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, is_verified, verification_token, verification_token_expiry, used_storage, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiry,
		&i.UsedStorage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, password_hash, is_verified, verification_token, verification_token_expiry, used_storage, created_at, updated_at FROM users WHERE verification_token = $1
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiry,
		&i.UsedStorage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserAsVerified = `-- name: MarkUserAsVerified :exec
UPDATE users
SET is_verified = TRUE, verification_token = NULL, verification_token_expiry = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkUserAsVerified(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markUserAsVerified, id)
	return err
}

const updateVerificationToken = `-- name: UpdateVerificationToken :exec
UPDATE users
SET verification_token = $1, verification_token_expiry = $2, updated_at = CURRENT_TIMESTAMP
WHERE email = $3
`

type UpdateVerificationTokenParams struct {
	VerificationToken       sql.NullString
	VerificationTokenExpiry sql.NullTime
	Email                   string
}

func (q *Queries) UpdateVerificationToken(ctx context.Context, arg UpdateVerificationTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateVerificationToken, arg.VerificationToken, arg.VerificationTokenExpiry, arg.Email)
	return err
}
